# Generated by Django 4.2 on 2025-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteluser',
            old_name='email_otp',
            new_name='email_token',
        ),
        migrations.RenameField(
            model_name='hotelvendor',
            old_name='email_otp',
            new_name='email_token',
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
